project:
  type: book
  output-dir: "docs"
  execute-dir: project
book:
  title: "what if"
  subtitle: "the What If relearn"
  author: "Congyuan He"
  date: "9/12/2024"
  
  sidebar:
    style: "docked" 
    collapse-level: 1 
    search: true 
    logo: images/dragon.png 

  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
        
  page-navigation: true
  repo-url: https://github.com/hcyhh/what_if
  
  chapters:
    - index.qmd
    - text: "---"
    - part: "I Causal inference without models"
      chapters: 
      - A definition of causal effect.qmd
      - Randomized experiments.qmd
      - Observation Study.qmd
      - Effect Modification.qmd
      - Interaction.qmd
      - Graphical representation of causal effects.qmd
      - Confounding.qmd
      - Selection bias.qmd
      - Measurement bias and “Noncausal” diagrams.qmd
      - Random variability.qmd
      - references.qmd
    - part: "II Causal inference with models"
      chapters: 
      - Why model.qmd
      - IP WEIGHTING AND MARGINAL STRUCTURAL MODELS.qmd
      - STANDARDIZATION AND THE PARAMETRIC G-FORMULA.qmd
    - text: "---"
    - part: "参考文献"
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

